### ISSUE TITLE
Supporting Project -> Update Project Source

### ISSUE THREAD

**Issue by JohnRoux** [JustSteveKing/laravel-envoyer-sdk#1]
**Is your feature request related to a problem? Please describe.**
Currently there's no way to update a project's source (https://envoyer.io/api-documentation#update-project-source)
This is currently the only way to programmatically control the "push to deploy" flag in envoyer.

**Describe the solution you'd like**
A updateSource method should be added to the Project class

**Comment by JohnRoux** [comment]
I realised this is actually a really nice and easy change since to the design. Busy testing and will make a PR if it's all looking good :+1:

**Comment by JustSteveKing** [comment]
Perfect thank you! I haven't checked the API for changes recently, so if it has changes a PR would be very welcome!
