### ISSUE TITLE
Array returned instead of object on invalid project create

### ISSUE THREAD

**Issue by ghost** [JustSteveKing/laravel-envoyer-sdk#3]
**Describe the bug**
An array is returned instead of the expected object:
`TypeError: Return value of JustSteveKing\Laravel\Envoyer\SDK\Resources\EnvoyerResource::save() must be an object or null, array returned in  /Users/username/Sites/project/vendor/juststeveking/laravel-envoyer-sdk/src/Resources/EnvoyerResource.php:50
`

This happens when the API returns an error, To reproduce it all you have to do is send some invalid data :). I'm not sure why though, because `json_decode` should return an object like it is in the code.

**Comment by JustSteveKing** [comment]
Thanks for this one @thatsalltheyare I will have a look into this!

**Comment by JustSteveKing** [comment]
@thatsalltheyare please see the latest release, hopefully this solved your problem! Sorry for the delay, my wife gave birth since I commented
